name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
  pull_request_target:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}
      NEXT_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_TOKEN }}

    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout code
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Check Lint
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3000

      - name: Collect test coverage report
        run: yarn coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
