name: Build

on: 
  push:
    branches: [main]
  pull_request:
    branches: [develop]

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}
      NEXT_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NPM dependencies
        run: npm install

      - name: Check Lint
        run: npm run lint

      - name: Run Test
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Collect test coverage report
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}